name: Discover Trending APIs

on:
  schedule:
    # Run monthly on the 1st at 00:30 UTC (6:00 AM IST on the 1st of each month)
    - cron: '30 0 1 * *'
  push:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  discover-apis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 feedparser
          
      - name: Run API discovery script
        run: python scripts/discover_trending_apis.py
        
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "gunjanjaswal@gmail.com"
          git config --local user.name "Gunjan Jaswaal"
          git add -A
          git commit -m "Discover new trending APIs [skip ci]"
          git push
