name: Manual Update

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Commit message'
        required: true
        default: 'Update README.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 markdown

      - name: Fix navigation links
        run: |
          python .github/scripts/fix-navigation-links.py

      - name: Create local changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "${{ github.event.inputs.message }}"

      - name: Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
