name: Handle Stale Issues

on:
  schedule:
    - cron: '30 1 * * *'  # Run daily at 1:30 UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.'
          close-issue-message: 'This issue was closed because it has been stale for 14 days with no activity. If this is still relevant, please feel free to reopen it or create a new issue.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,enhancement,bug'
          days-before-stale: 30
          days-before-close: 14
          operations-per-run: 100
          remove-stale-when-updated: true
