name: Update APIs

on:
  schedule:
    # Run weekly on Sunday at midnight UTC (5:30 AM Sunday IST)
    - cron: '0 0 * * 0'
  push:
    branches: [ main, master ]
  workflow_dispatch:
    # Allow manual triggering

jobs:
  update-apis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run API update script
        run: python scripts/update_apis.py
        
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and push if changed
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "gunjanjaswal@gmail.com"
          git config --local user.name "Gunjan Jaswaal"
          git add -A
          git commit -m "Auto-update APIs data [skip ci]"
          git push
