name: Weekly API Status Check

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays at 00:00 UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-apis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4
          
      - name: Run API discovery script
        run: python scripts/discover_trending_apis.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Weekly API update [automated] $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
